# Generated by Django 6.0.3 on 2026-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Entrada'), ('WITHDRAWAL', 'Saída')], max_length=10, verbose_name='Tipo de Transação')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
    ]
