# Generated by Django 6.0.3 on 2026-04-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança')], max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.bank')),
            ],
        ),
    ]
